language: swift
osx_image: xcode11.4
script: 
  xcodebuild clean build test -enableCodeCoverage YES -workspace Example/SQRichTextEditor.xcworkspace -scheme SQRichTextEditor-Example -sdk iphonesimulator13.4 -destination "platform=iOS Simulator,OS=13.4.1,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO